name: HomeGUI
version: 1.3.1
main: com.technovision.homegui.Homegui
api-version: 1.13
depend: [Essentials]
authors: [TechnoVision]
commands:
  home:
    description: Opens the HomeGUI screen.
    usage: /<command>
    aliases: homes
  h:
    description: Reloads the HomeGUI config.
    usage: /<command>
  sethome:
    description: Opens the SetHomeGUI screen.
    usage: /<command>